# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rename.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RenameFileWindow(object):
    def setupUi(self, RenameFileWindow):
        RenameFileWindow.setObjectName("RenameFileWindow")
        RenameFileWindow.resize(400, 130)
        self.centralwidget = QtWidgets.QWidget(RenameFileWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbCreateFile = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lbCreateFile.setFont(font)
        self.lbCreateFile.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lbCreateFile.setLineWidth(2)
        self.lbCreateFile.setMidLineWidth(2)
        self.lbCreateFile.setTextFormat(QtCore.Qt.AutoText)
        self.lbCreateFile.setScaledContents(False)
        self.lbCreateFile.setWordWrap(True)
        self.lbCreateFile.setObjectName("lbCreateFile")
        self.verticalLayout.addWidget(self.lbCreateFile)
        self.inputRenameFile = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.inputRenameFile.setMinimumSize(QtCore.QSize(0, 30))
        self.inputRenameFile.setText("")
        self.inputRenameFile.setObjectName("inputRenameFile")
        self.verticalLayout.addWidget(self.inputRenameFile)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 90, 231, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNext = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout.addWidget(self.btnNext)
        self.btnCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        RenameFileWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RenameFileWindow)
        QtCore.QMetaObject.connectSlotsByName(RenameFileWindow)

    def retranslateUi(self, RenameFileWindow):
        _translate = QtCore.QCoreApplication.translate
        RenameFileWindow.setWindowTitle(_translate("RenameFileWindow", "Rename File/Folder"))
        self.lbCreateFile.setText(_translate("RenameFileWindow", "Please enter the name of the file which should be created:"))
        self.btnNext.setText(_translate("RenameFileWindow", "Next"))
        self.btnCancel.setText(_translate("RenameFileWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RenameFileWindow = QtWidgets.QMainWindow()
    ui = Ui_RenameFileWindow()
    ui.setupUi(RenameFileWindow)
    RenameFileWindow.show()
    sys.exit(app.exec_())
